import {useEffect,useMemo,useRef,useState} from 'react'
import type {ReactNode} from 'react'
import type {Product,NegotiationResult} from './marketplace'
import {catalog,negotiate} from './marketplace'
import ProductDetail from './product-detail'
import WebMCPObservabilityPanel from './webmcp-observability-panel'
import './phase16-gamified-journey.css'
import './phase16-gamified-journey-overrides.css'

type Basket={products:Product[];deals:NegotiationResult[];total:number;saving:number}
type Props={phase:string;running:boolean;approved:boolean;products:Product[];proposal:Basket|null;goal?:string;budget?:number}
const stages=[['SEARCHING','SEARCH'],['ANALYZING','EVALUATE'],['NEGOTIATING','NEGOTIATE'],['CONSTITUTION CHECK','GOVERN'],['HUMAN APPROVAL','APPROVAL'],['EXECUTION RELEASED','EXECUTE']]
const descriptions=['Searching the marketplace','Evaluating mission-fit options','Negotiating with seller agents','Checking your constitution','Review and approve the proposed deal','Executing the approved transaction']
const phaseIndex=(p:string)=>{const i=stages.findIndex(([x])=>x===p);return i<0?(p==='NO COMPLIANT DEAL'?3:0):i}
function tick(){try{const A=window.AudioContext||((window as any).webkitAudioContext);if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=640;g.gain.value=.01;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch{}}
function Card({i,title,state,current,depth,children,onOpen}:{i:number;title:string;state:string;current:boolean;depth:number;children:ReactNode;onOpen:()=>void}){return <article className={`stage-stack-card ${current?'current':''} ${state==='done'?'completed':''} stack-depth-${Math.min(depth,5)}`}><button className="stage-card-head" onClick={()=>{tick();onOpen()}} aria-expanded={current}><span className="stage-number">{state==='done'?'✓':String(i+1).padStart(2,'0')}</span><span className="stage-copy"><span>STAGE {String(i+1).padStart(2,'0')}</span><strong>{title}</strong></span><span className="stage-state">{state==='done'?'DONE':current?'ACTIVE':'READY'}</span><span className="stage-chevron">›</span></button>{current&&<div className="stage-card-body">{children}</div>}</article>}

export default function AgentJourneyGamified({phase,running,approved,products,proposal,budget=0}:Props){
 const target=approved?5:phaseIndex(phase)
 const [open,setOpen]=useState(target)
 const [working,setWorking]=useState<Basket|null>(proposal)
 const [detail,setDetail]=useState<{product:Product;deal?:NegotiationResult}|null>(null)
 const [basketReview,setBasketReview]=useState(false)
 const [declined,setDeclined]=useState(false)
 const [negotiationProduct,setNegotiationProduct]=useState(0)
 const [negotiationMessage,setNegotiationMessage]=useState(-1)
 const [negotiationDone,setNegotiationDone]=useState(false)
 const stackRef=useRef<HTMLDivElement>(null)
 const basket=working??proposal
 const reviewProducts=basket?.products??products
 const alternatives=useMemo(()=>catalog.filter(p=>!reviewProducts.some(x=>x.id===p.id)&&reviewProducts.some(x=>x.category===p.category)&&(!budget||p.price<=budget)).sort((a,b)=>b.rating-a.rating).slice(0,5),[reviewProducts,budget])
 const threads=useMemo(()=>basket?.products.map((product,i)=>({product,deal:basket.deals[i]})).filter(x=>x.deal?.transcript?.length)??[],[basket])
 const journeyTarget=(!approved&&target>=3&&!negotiationDone)?2:target
 useEffect(()=>{setWorking(proposal);setDeclined(false);setBasketReview(false);setDetail(null)},[proposal])
 // Focus ONLY the six-stage journey stack. Do not scroll the page or any parent/support panel.
 useEffect(()=>{if(open<0)return;const node=stackRef.current;if(!node)return;const card=node.querySelector<HTMLElement>('.stage-stack-card.current');if(!card)return;const stackTop=node.getBoundingClientRect().top;const cardTop=card.getBoundingClientRect().top;const delta=cardTop-stackTop-16;node.scrollTo({top:Math.max(0,node.scrollTop+delta),behavior:'smooth'})},[open])
 useEffect(()=>{if(open!==2||!threads.length){setNegotiationProduct(0);setNegotiationMessage(-1);setNegotiationDone(false);return}setNegotiationProduct(0);setNegotiationMessage(-1);setNegotiationDone(false)},[open,threads.length])
 useEffect(()=>{if(open!==2||!threads.length||negotiationDone)return;const thread=threads[negotiationProduct];if(!thread){setNegotiationDone(true);return}if(negotiationMessage<thread.deal.transcript.length-1){const id=window.setTimeout(()=>{setNegotiationMessage(n=>n+1);tick()},2200);return()=>window.clearTimeout(id)}if(negotiationProduct<threads.length-1){const id=window.setTimeout(()=>{setNegotiationProduct(n=>n+1);setNegotiationMessage(-1);tick()},3200);return()=>window.clearTimeout(id)}const id=window.setTimeout(()=>setNegotiationDone(true),3000);return()=>window.clearTimeout(id)},[open,threads,negotiationProduct,negotiationMessage,negotiationDone])
 useEffect(()=>{if(!running)return;if(open===4||approved)return;if(open===2&&!negotiationDone)return;if(open!==journeyTarget){const id=window.setTimeout(()=>setOpen(journeyTarget),800);return()=>window.clearTimeout(id)}},[running,open,journeyTarget,negotiationDone,approved])
 const openProduct=(p:Product)=>{const i=basket?.products.findIndex(x=>x.id===p.id)??-1;setDetail({product:p,deal:i>=0?basket?.deals[i]:undefined});tick()}
 const replace=(oldId:string,next:Product)=>{if(!basket)return;const i=basket.products.findIndex(p=>p.id===oldId);if(i<0)return;const deal=negotiate(next,budget);const ps=[...basket.products];const ds=[...basket.deals];ps[i]=next;ds[i]=deal;setWorking({products:ps,deals:ds,total:ds.reduce((s,d)=>s+d.acceptedPrice,0),saving:ds.reduce((s,d)=>s+d.saving,0)});tick()}
 const remove=(id:string)=>{if(!basket)return;const i=basket.products.findIndex(p=>p.id===id);if(i<0)return;const ps=basket.products.filter(p=>p.id!==id);const ds=basket.deals.filter((_,n)=>n!==i);setWorking({products:ps,deals:ds,total:ds.reduce((s,d)=>s+d.acceptedPrice,0),saving:ds.reduce((s,d)=>s+d.saving,0)});tick()}
 const add=(p:Product)=>{const d=negotiate(p,budget);const ps=[...(basket?.products??[]),p];const ds=[...(basket?.deals??[]),d];setWorking({products:ps,deals:ds,total:ds.reduce((s,x)=>s+x.acceptedPrice,0),saving:ds.reduce((s,d)=>s+d.saving,0)});tick()}
 const approve=()=>{tick();window.dispatchEvent(new CustomEvent('aeon:approve-mission',{detail:basket??proposal}))}
 const decline=()=>{tick();setDeclined(true);window.dispatchEvent(new CustomEvent('aeon:decline-mission',{detail:basket??proposal}))}
 const visible=threads[negotiationProduct]?.deal.transcript.slice(0,Math.max(0,negotiationMessage+1))??[]
 const stageBody=(i:number):ReactNode=>{
  if(i===0)return <><p>AEON is scanning the connected marketplace for products that match the mission.</p><div className="search-pills">{products.slice(0,5).map(p=><button className="search-pill" key={p.id} onClick={()=>openProduct(p)}><span className="mini-orb">✦</span><div><b>{p.name}</b><small>{p.category} · ₦{p.price.toLocaleString()}</small></div></button>)}</div></>
  if(i===1)return <><p>Comparing mission fit, price, availability and your stated priorities.</p><div className="thinking-bars"><i/><i/><i/></div></>
  if(i===2)return <><p>AEON negotiates separately with each seller agent. Watch the conversation unfold in real time.</p>{threads.length?<div className="negotiation-live-stage"><div className="negotiation-live-meta"><span>SELLER {negotiationProduct+1} OF {threads.length}</span><b>{threads[negotiationProduct].product.name}</b><i>{negotiationDone?'CONVERSATION COMPLETE':'LIVE CONVERSATION'}</i></div><div className="live-chat-window">{visible.map((m,j)=><div className={`thread-message live-message ${m.speaker.toLowerCase().replace(/\s+/g,'-')}`} key={`${m.round}-${j}`}><small>{m.speaker} · ROUND {m.round}</small><p>{m.text}</p>{m.price!==undefined&&<b>₦{m.price.toLocaleString()}</b>}</div>)}{!negotiationDone&&<div className="typing-indicator"><span/><span/><span/> {negotiationMessage%2===0?'Seller agent is typing…':'AEON is typing…'}</div>}</div><div className="negotiation-progress">{threads.map((x,j)=><span key={x.product.id} className={j<negotiationProduct?'done':j===negotiationProduct?'active':''}>{j+1}</span>)}</div></div>:<div className="chat-preview"><div className="chat-bubble">Waiting to contact seller agents…</div></div>}</>
  if(i===3)return <><p>Checking every proposed total against your mission authority before asking for permission.</p><div className="offer-line"><span>CONSTITUTION</span><strong>{basket&&budget>0&&basket.total>budget?'BLOCKED':'COMPLIANT'}</strong></div></>
  if(i===4){if(declined)return <div className="decline-state"><strong>Deal declined by you.</strong><p>AEON has not authorized or executed any purchase.</p></div>;return <><p>AEON has stopped. Review the exact recommendation. Remove items, switch alternatives, inspect products, or decline. Nothing is purchased until you approve.</p><div className="review-summary"><strong>{reviewProducts.length===1?'Review 1 product':`${reviewProducts.length} products in proposed basket`}</strong><small>{reviewProducts.length>1?'Remove, replace or inspect any item before approving.':'Inspect the primary recommendation or switch to an alternative.'}</small></div><div className="journey-actions">{reviewProducts.length>1?<button className="tactile-button" onClick={()=>setBasketReview(true)}>Review basket</button>:reviewProducts.length===1?<button className="tactile-button" onClick={()=>openProduct(reviewProducts[0])}>Review product</button>:null}<button className="tactile-button primary-action" onClick={approve}>Approve deal →</button><button className="tactile-button danger-action" onClick={decline}>Don't approve</button></div></>}
  return <><p>The approved proposal is authorized for execution.</p><div className="offer-line"><span>EXECUTION</span><strong>{approved?'RELEASED':'LOCKED'}</strong></div>
 }
 return <section className="gamified-journey" aria-live="polite"><div className="journey-top"><div><span className="journey-kicker">AEON · AGENT JOURNEY</span><h2>{approved?'Execution released.':declined?'Purchase not approved.':running?'Agent is working…':'Deal ready.'}</h2><p>{descriptions[open]??'Agent journey'}</p></div><div className="journey-signal"><span className="journey-orb"/>{open===4&&!approved&&!declined?'YOUR DECISION':declined?'DECLINED':running?'LIVE':'OBSERVING'}</div></div>
 <div className="stage-stack" ref={stackRef} role="list">{stages.map(([name,label],i)=><Card key={name} i={i} title={label} state={i<target?'done':i===target?'active':'ready'} current={i===open} depth={Math.min(Math.abs(i-open),5)} onOpen={()=>setOpen(i)}>{stageBody(i)}</Card>)}</div>
 <div className="journey-observability"><WebMCPObservabilityPanel/></div><div className="stack-nav" aria-label="Journey navigation">{stages.map(([,label],i)=><button key={label} className={i===open?'active':''} onClick={()=>setOpen(i)} aria-label={`View ${label}`}>{i+1}</button>)}</div><div className="stack-foot">The active stage is centered and focused. The next stages remain visible behind it; tap a visible card to peek.</div>
 {detail&&<ProductDetail product={detail.product} deal={detail.deal} alternatives={alternatives} onSelectAlternative={p=>{replace(detail.product.id,p);setDetail({product:p,deal:negotiate(p,budget)})}} onBack={()=>setDetail(null)} onApprove={open===4&&!declined?approve:undefined}/>} 
 {basketReview&&basket&&<div className="basket-review-page" role="dialog" aria-modal="true"><div className="basket-review-shell"><header className="basket-review-head"><button className="detail-back" onClick={()=>setBasketReview(false)}>← Back to mission</button><span className="journey-kicker">AEON · BASKET REVIEW</span></header><div className="basket-review-content"><div className="basket-review-hero"><span className="journey-kicker">PROPOSED BASKET</span><h1>{basket.products.length} {basket.products.length===1?'product':'products'}</h1><p>This is your editable purchase proposal. Nothing is authorized yet.</p></div><div className="basket-review-list">{basket.products.map((p,i)=><div className="basket-review-row" key={p.id}><button className="basket-row-main" onClick={()=>{setBasketReview(false);openProduct(p)}}><span>{String(i+1).padStart(2,'0')}</span><div><b>{p.name}</b><small>{p.category} · {p.merchant}</small></div><strong>₦{basket.deals[i]?.acceptedPrice.toLocaleString()??p.price.toLocaleString()}</strong><i>›</i></button><button className="basket-remove" onClick={()=>remove(p.id)}>Remove</button><div className="basket-alts">{catalog.filter(a=>a.category===p.category&&a.id!==p.id&&!basket.products.some(x=>x.id===a.id)&&(!budget||a.price<=budget)).slice(0,3).map(a=><button key={a.id} onClick={()=>replace(p.id,a)}>Switch to {a.name} · ₦{a.price.toLocaleString()}</button>)}</div></div>)}</div>{alternatives.length>0&&<section className="basket-add"><span className="journey-kicker">AVAILABLE ALTERNATIVES</span><h3>Add another option</h3><div>{alternatives.map(a=><button key={a.id} onClick={()=>add(a)}><b>{a.name}</b><small>₦{a.price.toLocaleString()} · ★ {a.rating}</small></button>)}</div></section>}<div className="basket-review-total"><span>Current total</span><strong>₦{basket.total.toLocaleString()}</strong>{basket.saving>0&&<small>Saving ₦{basket.saving.toLocaleString()}</small>}</div><div className="journey-actions"><button className="tactile-button" onClick={()=>setBasketReview(false)}>Keep reviewing</button><button className="tactile-button primary-action" disabled={!basket.products.length||!!(budget&&basket.total>budget)} onClick={approve}>Approve deal →</button><button className="tactile-button danger-action" onClick={()=>{setBasketReview(false);decline()}}>Don't approve</button></div></div></div></div>}
 </section>
}