import { useState } from 'react'
import { aeonTools } from './webmcp'

export default function AgentConsole(){
 const [selected,setSelected]=useState(aeonTools[0].name)
 const [showDetails,setShowDetails]=useState(false)
 const tool=aeonTools.find(t=>t.name===selected)!
 const sample=selected==='search_products'?{query:'creator setup performance audio',maxPrice:1000000}:selected==='compare_products'?{productIds:['creator-kit-01','creator-kit-02'],priorities:['performance','audio quality','budget']}:selected==='request_purchase_approval'?{productId:'creator-kit-01',price:749000,reason:'Purchase requires human approval'}:{goal:'Build the best creator setup',budget:1000000,canNegotiate:true,purchaseRequiresApproval:true}
 return <section className="agent-console"><div className="console-head"><div><div className="kicker">WEBMCP / AGENT CONSOLE</div><h2>AEON exposes capabilities, not clicks.</h2></div><span className="console-status">● TOOLING ONLINE</span></div><div className="console-grid"><nav className="tool-list">{aeonTools.map(t=><button className={t.name===selected?'selected':''} onClick={()=>{setSelected(t.name);setShowDetails(false)}} key={t.name}><span>↳</span>{t.name}</button>)}</nav><div className="tool-detail"><div className="tool-title"><span className="tool-badge">WEBMCP READY</span><h3>{tool.name}</h3></div><p>{tool.description}</p><div className="capability-summary"><span className="capability-icon">✦</span><div><strong>Available to agents</strong><small>AEON can call this capability directly through WebMCP.</small></div><span className="capability-status">ONLINE</span></div><div className="authority-note"><span>HUMAN AUTHORITY</span><p>AEON can use capabilities autonomously, but consequential purchases remain under your approval.</p></div><button className="technical-toggle" onClick={()=>setShowDetails(v=>!v)} aria-expanded={showDetails}>{showDetails?'Hide technical details':'View technical details'} <span>{showDetails?'↑':'↓'}</span></button>{showDetails&&<div className="io technical-details"><div><label>INPUT</label><pre>{JSON.stringify(sample,null,2)}</pre></div><div><label>SCHEMA</label><pre>{JSON.stringify(tool.inputSchema,null,2)}</pre></div></div>}</div></div></section>
}
