import {useEffect,useState} from 'react'
import type {Product,NegotiationResult} from './marketplace'
import './phase16-gamified-journey.css'
type Basket={products:Product[];deals:NegotiationResult[];total:number;saving:number}
type Props={phase:string;running:boolean;approved:boolean;products:Product[];proposal:Basket|null}
const stages=[['SEARCHING','SEARCH'],['ANALYZING','EVALUATE'],['NEGOTIATING','NEGOTIATE'],['CONSTITUTION CHECK','GOVERN'],['HUMAN APPROVAL','APPROVAL'],['EXECUTION RELEASED','EXECUTE']]
const idx=(p:string)=>Math.max(0,stages.findIndex(([x])=>x===p))
function sound(){try{const A=window.AudioContext||((window as any).webkitAudioContext);if(!A)return;const c=new A();const o=c.createOscillator(),g=c.createGain();o.frequency.value=620;o.type='sine';g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.025,c.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.08);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.09)}catch{}}
function Card({i,title,state,current,children,onOpen}:{i:number;title:string;state:string;current:boolean;children?:React.ReactNode;onOpen:()=>void}){return <article className={`stage-stack-card ${current?'current':''} ${state==='done'?'completed':''}`}><div className="stage-card-head" onClick={()=>{sound();onOpen()}}><span className="stage-number">{state==='done'?'✓':String(i+1).padStart(2,'0')}</span><div className="stage-copy"><span>STAGE {String(i+1).padStart(2,'0')}</span><strong>{title}</strong></div><span className="stage-state">{state==='done'?'DONE':current?'ACTIVE':'READY'}</span><span className="stage-chevron">›</span></div>{current&&<div className="stage-card-body">{children}</div>}</article>}
export default function AgentJourneyGamified({phase,running,approved,products,proposal}:Props){const target=approved?5:idx(phase);const [open,setOpen]=useState(target);useEffect(()=>setOpen(running?0:target),[running,target]);const names=['Searching the marketplace','Evaluating mission-fit options','Negotiating with seller agents','Checking your constitution','Waiting for your decision','Execution authority released'];return <section className="gamified-journey" aria-live="polite"><div className="journey-top"><div><span className="journey-kicker">AEON · AGENT JOURNEY</span><h2>{approved?'Deal approved.':phase==='NO COMPLIANT DEAL'?'Mission paused.':running?'Agent is working…':'Deal ready.'}</h2><p>{approved?'Execution is now authorized.':names[open]}</p></div><div className="journey-signal"><span className="journey-orb"/>{running?'LIVE':'OBSERVING'}</div></div>{stages.map(([phaseName,label],i)=>{const done=i<target;const current=i===open;return <Card key={phaseName} i={i} title={label} state={done?'done':i===target?'active':'ready'} current={current} onOpen={()=>setOpen(i)}>{i===0&&<><p>AEON is scanning for products that actually match your request.</p><div className="search-pills">{products.slice(0,4).map((p)=><div className="search-pill" key={p.id}><span className="mini-orb">✦</span><div><b>{p.name}</b><small>{p.category} · ₦{p.price.toLocaleString()}</small></div></div>)}</div></>}{i===1&&<><p>Comparing price, requirements and your stated priorities.</p><div className="thinking-bars"><i/><i/><i/></div></>}{i===2&&<><p>AEON is asking the seller agent for a better deal instead of silently accepting the listing.</p>{proposal&&<div className="offer-line"><span>BEST NEGOTIATED OFFER</span><strong>₦{proposal.total.toLocaleString()}</strong>{proposal.saving>0&&<small>−₦{proposal.saving.toLocaleString()}</small>}</div>}<div className="chat-preview"><div className="chat-bubble">Can you improve the offer?</div><div className="chat-bubble seller">Here is my best price.<small>Seller agent response</small></div></div></>}{i===3&&<><p>Checking budget, negotiation authority and purchase rules before anything consequential happens.</p><div className="offer-line"><span>CONSTITUTION</span><strong>COMPLIANT</strong></div></>}{i===4&&<><p>AEON has stopped. Your decision is required before purchase.</p><div className="journey-actions"><button className="tactile-button" onClick={sound}>Inspect basket</button><button className="tactile-button" onClick={sound}>Review products</button><button className="tactile-button primary-action" onClick={sound}>Approve deal →</button></div></>}{i===5&&<><p>The approved basket is authorized for execution.</p><div className="offer-line"><span>EXECUTION</span><strong>{approved?'RELEASED':'LOCKED'}</strong></div></>}</Card>})}<div className="stack-foot">Tap any completed stage to revisit it · AEON keeps the details available without putting everything on screen.</div></section>}
