import { useEffect, useState } from 'react'
import { getMissionConstitution, subscribeMissionConstitution, MissionConstitution } from './mission-state'
import { aeonTools } from './webmcp'
type FirewallEvent={id:number;stage:'REQUESTED'|'EVALUATING'|'VIOLATION'|'BLOCKED';title:string;detail:string;time:string}
export default function ConstitutionFirewall(){
 const [constitution,setConstitution]=useState<MissionConstitution>(getMissionConstitution()); const [events,setEvents]=useState<FirewallEvent[]>([])
 useEffect(()=>subscribeMissionConstitution(setConstitution),[])
 const attemptNegotiation=async()=>{const tool=aeonTools.find(t=>t.name==='negotiate_offer')!;const id=Date.now();const add=(e:Omit<FirewallEvent,'id'|'time'>)=>setEvents(x=>[...x,{...e,id:id+x.length,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}]);add({stage:'REQUESTED',title:'Agent requested negotiation',detail:'negotiate_offer → Creator Studio Kit'});await new Promise(r=>setTimeout(r,350));add({stage:'EVALUATING',title:'Constitution evaluated',detail:`Budget ₦${constitution.budget.toLocaleString()} · Negotiation ${constitution.canNegotiate?'AUTHORIZED':'LOCKED'}`});await new Promise(r=>setTimeout(r,350));const result:any=await tool.execute({productId:'creator-kit-01',budget:constitution.budget});if(result.status==='blocked'){add({stage:'VIOLATION',title:'Rule violated',detail:result.reason});await new Promise(r=>setTimeout(r,250));add({stage:'BLOCKED',title:'Action blocked',detail:result.message})}else add({stage:'BLOCKED',title:'Action allowed',detail:'Constitution passed; negotiation engine executed.'})}
 return <div className="firewall panel"><div className="firewall-head"><div><div className="kicker">AEON / CONSTITUTION FIREWALL</div><h3>Governance at the tool boundary</h3><p className="muted">The agent can request an action. The constitution decides whether execution is allowed.</p></div><span className="firewall-status">● FIREWALL ACTIVE</span></div><div className="firewall-rule"><span>ACTIVE RULE</span><b>NEGOTIATION: {constitution.canNegotiate?'AUTHORIZED':'DENIED'}</b><b>CEILING: ₦{constitution.budget.toLocaleString()}</b></div><button className="firewall-test" onClick={attemptNegotiation}>SIMULATE AGENT NEGOTIATION →</button><div className="firewall-stream">{events.length===0?<div className="firewall-empty">No intercepted actions yet.<br/><strong>Trigger a negotiation to watch the constitution execute.</strong></div>:events.map((e,i)=><div className={`firewall-event ${e.stage.toLowerCase()}`} key={e.id}><span className="firewall-index">{String(i+1).padStart(2,'0')}</span><span className="firewall-icon">{e.stage==='BLOCKED'?'×':e.stage==='VIOLATION'?'!':e.stage==='EVALUATING'?'◇':'→'}</span><div><b>{e.title}</b><small>{e.detail}</small></div><time>{e.time}</time></div>)}</div></div>
}