import { useMemo, useState } from 'react'
import { catalog, negotiate, rankForMission } from './marketplace'
export default function MarketplaceView(){
 const [query,setQuery]=useState('creator'); const [budget,setBudget]=useState(1000000); const [selected,setSelected]=useState(catalog[0]); const [negotiated,setNegotiated]=useState<any>(null)
 const products=useMemo(()=>rankForMission(catalog.filter(p=>p.price<=budget),['performance','audio quality']),[budget])
 const visible=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())||query==='creator')
 const runNegotiation=()=>setNegotiated(negotiate(selected,budget))
 return <section className="marketplace-view"><div className="market-head"><div><div className="kicker">AEON MARKETPLACE</div><h1>Where agents shop<br/><em>with you.</em></h1><p className="muted">Products are exposed as structured capabilities. AEON can search, rank and negotiate without guessing through a UI.</p></div><div className="market-status">● WEBMCP MARKET LIVE</div></div><div className="market-controls"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the marketplace"/><span>MISSION BUDGET <b>₦{budget.toLocaleString()}</b></span><input type="range" min="100000" max="1500000" step="50000" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></div><div className="market-grid"><div className="product-grid">{visible.map(p=><button className={`product-card ${selected.id===p.id?'selected':''}`} onClick={()=>{setSelected(p);setNegotiated(null)}} key={p.id}><div className="product-art">AEON / {p.category.toUpperCase()}</div><div className="product-meta"><span>{p.category}</span><span>★ {p.rating}</span></div><h3>{p.name}</h3><p>Performance {p.performance} · Audio {p.audio}</p><strong>₦{p.price.toLocaleString()}</strong><small>{p.negotiable?'NEGOTIABLE':'FIXED'} · {p.stock} AVAILABLE</small></button>)}</div><aside className="deal-panel"><div className="deal-label">AGENT RECOMMENDATION</div><h2>{selected.name}</h2><div className="score">{selected.performance + selected.audio >= 190 ? 'BEST MATCH' : 'STRONG MATCH'} <span>MISSION FIT</span></div><div className="deal-row"><span>Listed</span><b>₦{selected.price.toLocaleString()}</b></div><div className="deal-row"><span>Performance</span><b>{selected.performance}/100</b></div><div className="deal-row"><span>Audio</span><b>{selected.audio}/100</b></div><button className="negotiate" onClick={runNegotiation} disabled={!selected.negotiable}>{selected.negotiable?'NEGOTIATE WITH MERCHANT ↗':'FIXED PRICE'}</button>{negotiated&&<div className="negotiation-result"><span>NEGOTIATION COMPLETE · {negotiated.rounds} ROUNDS</span><strong>₦{negotiated.acceptedPrice.toLocaleString()}</strong><p>{negotiated.message}</p>{negotiated.saving>0&&<b className="saving">You saved ₦{negotiated.saving.toLocaleString()}</b>}</div>}<div className="deal-state"><span className="state-dot"/> {negotiated?'DEAL PREPARED · HUMAN APPROVAL REQUIRED':'NO DEAL YET'}</div></aside></div></section>
}
