import { getMissionConstitution, MissionConstitution } from './mission-state'
export type Product={id:string;name:string;category:string;price:number;originalPrice:number;merchant:string;rating:number;performance:number;audio:number;stock:number;negotiable:boolean}
export const catalog:Product[]=[
{id:'creator-kit-01',name:'Creator Studio Kit',category:'Creator Kit',price:749000,originalPrice:799000,merchant:'AEON Marketplace',rating:4.9,performance:96,audio:94,stock:8,negotiable:true},
{id:'creator-kit-02',name:'Pro Creator Stack',category:'Creator Kit',price:895000,originalPrice:950000,merchant:'AEON Marketplace',rating:4.8,performance:98,audio:91,stock:5,negotiable:true},
{id:'creator-kit-03',name:'Mobile Creator Kit',category:'Creator Kit',price:529000,originalPrice:559000,merchant:'AEON Marketplace',rating:4.7,performance:88,audio:89,stock:14,negotiable:false},
{id:'creator-kit-04',name:'Audio-first Creator Rig',category:'Creator Kit',price:679000,originalPrice:720000,merchant:'AEON Marketplace',rating:4.9,performance:90,audio:99,stock:4,negotiable:true},
{id:'camera-01',name:'AEON Creator Camera',category:'Camera',price:315000,originalPrice:339000,merchant:'AEON Marketplace',rating:4.8,performance:96,audio:82,stock:9,negotiable:true},
{id:'mic-01',name:'Studio USB Microphone',category:'Microphone',price:85000,originalPrice:99000,merchant:'AEON Marketplace',rating:4.8,performance:86,audio:98,stock:16,negotiable:true},
{id:'light-01',name:'Creator LED Light',category:'Lighting',price:65000,originalPrice:75000,merchant:'AEON Marketplace',rating:4.7,performance:82,audio:80,stock:20,negotiable:false},
{id:'tripod-01',name:'Pro Creator Tripod',category:'Support',price:55000,originalPrice:65000,merchant:'AEON Marketplace',rating:4.7,performance:84,audio:80,stock:18,negotiable:false},
{id:'phone-01',name:'AEON Pro Phone 256GB',category:'Phone',price:399000,originalPrice:429000,merchant:'AEON Marketplace',rating:4.8,performance:94,audio:91,stock:12,negotiable:true},
{id:'phone-02',name:'AEON Creator Phone Max',category:'Phone',price:489000,originalPrice:529000,merchant:'AEON Marketplace',rating:4.9,performance:97,audio:94,stock:7,negotiable:true},
{id:'phone-03',name:'AEON Lite Phone',category:'Phone',price:229000,originalPrice:249000,merchant:'AEON Marketplace',rating:4.5,performance:82,audio:84,stock:20,negotiable:false}
]
export function searchCatalog(query:string,maxPrice?:number){const q=query.toLowerCase();return catalog.filter(p=>(!maxPrice||p.price<=maxPrice)&&([p.name,p.category,p.merchant].join(' ').toLowerCase().includes(q)||q.includes('creator')||q.includes('phone')||q.includes('mobile'))).sort((a,b)=>b.rating-a.rating)}
const creatorParts=['Camera','Microphone','Lighting','Support']
export function searchMissionRequirements(goal:string,budget:number){const q=goal.toLowerCase();const requirements:string[]=[];if(/creator|content|studio|audio|video|stream/i.test(q)){requirements.push('Camera','Microphone','Lighting','Support')}if(/phone|smartphone|iphone|mobile/i.test(q))requirements.push('Phone');if(!requirements.length)requirements.push('Mission fit');return requirements.map(category=>{const products=searchCatalog(category,budget);return {category,products}})}
export type NegotiationResult={acceptedPrice:number;saving:number;rounds:number;message:string;status:'approved'|'rejected';reason?:string}
export function negotiate(product:Product,budget:number,constitution:MissionConstitution=getMissionConstitution()):NegotiationResult{if(!constitution.canNegotiate)return {acceptedPrice:product.price,saving:0,rounds:0,status:'rejected',message:'AEON blocked this negotiation.',reason:'CONSTITUTION_NEGOTIATION_DISABLED'};if(product.price>constitution.budget||budget>constitution.budget)return {acceptedPrice:product.price,saving:0,rounds:0,status:'rejected',message:'AEON blocked this offer because it exceeds the mission budget.',reason:'CONSTITUTION_BUDGET_EXCEEDED'};if(!product.negotiable)return {acceptedPrice:product.price,saving:0,rounds:0,status:'rejected',message:'Merchant does not accept negotiation.',reason:'MERCHANT_FIXED_PRICE'};const ceiling=Math.min(product.price,budget,constitution.budget);const floor=Math.max(Math.round(product.originalPrice*.84/1000)*1000,Math.round(product.price*.90/1000)*1000);const accepted=Math.min(ceiling,Math.max(floor,Math.round(product.price*.94/1000)*1000));if(accepted>constitution.budget)return {acceptedPrice:accepted,saving:0,rounds:2,status:'rejected',message:'AEON refused to propose a deal above the constitutional budget.',reason:'PROPOSED_PRICE_ABOVE_LIMIT'};return {acceptedPrice:accepted,saving:product.price-accepted,rounds:2,status:'approved',message:`AEON negotiated within the mission constitution and secured ₦${(product.price-accepted).toLocaleString()} savings.`}}
export function rankForMission(products:Product[],priorities:string[]){return [...products].map(p=>({...p,matchScore:Math.round(((priorities.includes('performance')?p.performance:80)*.4+(priorities.includes('audio quality')?p.audio:80)*.4+p.rating*20*.2))})).sort((a,b)=>b.matchScore-a.matchScore)}
