import { useState } from 'react'
import './app.css'

type Step = 'intent' | 'constitution' | 'live'
const demoMission = 'Build me the best creator setup under ₦1,000,000. Prioritize performance and audio quality. You can negotiate, but ask me before purchasing.'

export default function Mission() {
  const [step,setStep]=useState<Step>('intent')
  const [mission,setMission]=useState(demoMission)
  const [budget,setBudget]=useState(1000000)
  const [negotiate,setNegotiate]=useState(true)
  const [approved,setApproved]=useState(false)
  return <div className="mission"><aside className="side"><div className="brand"><span className="mark">A</span> AEON</div><div className={`step ${step==='intent'?'active':''}`}><span className="step-num">01</span><span>INTENT</span></div><div className={`step ${step==='constitution'?'active':''}`}><span className="step-num">02</span><span>CONSTITUTION</span></div><div className={`step ${step==='live'?'active':''}`}><span className="step-num">03</span><span>MISSION CONTROL</span></div><div className="side-foot">HUMAN AUTHORITY<br/>REMAINS WITH YOU<br/><br/>AEON / 0.1</div></aside><main className="content"><button className="back" onClick={()=>window.location.href='/'}>← AEON</button>
  {step==='intent' && <><div className="kicker">01 / DEFINE INTENT</div><h1>What do you want<br/>your agent to accomplish?</h1><p className="muted">Don't think about products. Describe the outcome. AEON will turn your intent into an executable mission.</p><textarea className="mission-input" value={mission} onChange={e=>setMission(e.target.value)}/><div className="row"><span className="counter">{mission.length} / 2,000</span><button className="continue" onClick={()=>setStep('constitution')}>DEFINE BOUNDARIES →</button></div></>}
  {step==='constitution' && <><div className="kicker">02 / AGENT CONSTITUTION</div><h1>Give your agent<br/>its boundaries.</h1><p className="muted">These rules are authority. AEON can act autonomously inside them — and must stop when it reaches a protected action.</p><div className="constitution"><div className="panel"><h3>MISSION AUTHORITY</h3><p>What this agent is allowed to do.</p><div className="rule"><div><strong>Search & compare</strong><p>Autonomous</p></div><div className="toggle on"/></div><div className="rule"><div><strong>Negotiate offers</strong><p>Within budget</p></div><button className={`toggle ${negotiate?'on':''}`} onClick={()=>setNegotiate(!negotiate)}/></div><div className="rule"><div><strong>Purchase</strong><p>Always ask me first</p></div><div className="toggle"/></div></div><div className="panel"><h3>MAXIMUM BUDGET</h3><div className="budget">₦{budget.toLocaleString()}</div><input className="slider" type="range" min="100000" max="1500000" step="50000" value={budget} onChange={e=>setBudget(Number(e.target.value))}/><p style={{marginTop:18}}>Priority: <strong>Performance + Audio</strong></p><button className="continue deploy" onClick={()=>setStep('live')}>DEPLOY AGENT ↗</button></div></div></>}
  {step==='live' && <><div className="kicker">03 / MISSION CONTROL · LIVE</div><h1>Your agent is<br/>on the hunt.</h1><div className="agent-card"><span className="pulse"/><div><strong>AEON-001</strong><div className="muted">Autonomous commerce agent · ACTIVE</div></div></div><div className="mission-live"><div className="panel"><h3>ACTIVITY STREAM</h3><div className="event current"><span className="event-dot"/><div><b>Searching the open web</b><small>Discovering creator hardware within ₦{budget.toLocaleString()}</small></div></div><div className="event current"><span className="event-dot"/><div><b>Comparing candidates</b><small>Performance and audio weighted highest</small></div></div><div className="event"><span className="event-dot"/><div><b>Negotiation</b><small>{negotiate?'Authorized within constitution':'Disabled by constitution'}</small></div></div><div className="event"><span className="event-dot"/><div><b>Purchase authorization</b><small>Human approval required</small></div></div></div><div><div className="constitution-mini"><h4>YOUR CONSTITUTION</h4><p>Budget <b>₦{budget.toLocaleString()}</b></p><p>Negotiation <b>{negotiate?'ON':'OFF'}</b></p><p>Purchase <b>ASK FIRST</b></p><p>Priority <b>Performance + Audio</b></p></div><div className="approval"><b>Human checkpoint</b><span className="muted">The agent cannot purchase without your approval.</span><button onClick={()=>setApproved(true)}>{approved?'APPROVED FOR DEMO':'VIEW PROPOSED DEAL'}</button></div></div></div></>}
 </main></div>
}
