import { searchCatalog, rankForMission, negotiate, searchMissionRequirements, Product } from './marketplace'
import { getMissionConstitution } from './mission-state'
import { emitAgentActivity } from './agent-activity'
type Tool={name:string;description:string;inputSchema:Record<string,unknown>;execute:(input:any)=>Promise<unknown>}
const blocked=(reason:string,message:string,tool='unknown')=>{emitAgentActivity({stage:'VIOLATION',title:'Rule violated',detail:reason,tool,reason});emitAgentActivity({stage:'BLOCKED',title:'Action blocked',detail:message,tool,reason});return {status:'blocked',blockedBy:'AEON_CONSTITUTION',reason,message}}
const keywords=(goal:string)=>goal.toLowerCase()
const composeBasket=(goal:string,budget:number,priorities:string[])=>{const requirements=searchMissionRequirements(goal,budget);const missing=requirements.filter(r=>!r.products.length).map(r=>r.category);const ranked=requirements.map(r=>({category:r.category,candidates:rankForMission(r.products,priorities)}));const picked:Product[]=[];let remaining=budget;for(const group of ranked){const candidate=group.candidates.find(p=>p.price<=remaining);if(candidate){picked.push(candidate);remaining-=candidate.price}}return {requirements:ranked,missing,selected:picked,total:picked.reduce((s,p)=>s+p.price,0),remaining,budget,complete:missing.length===0&&picked.length===requirements.length}}
export const aeonTools:Tool[]=[
{name:'create_mission',description:'Create an AEON mission with a goal, budget and authority boundaries.',inputSchema:{type:'object',properties:{goal:{type:'string'},budget:{type:'number'},canNegotiate:{type:'boolean'},purchaseRequiresApproval:{type:'boolean'}},required:['goal','budget']},execute:async(input)=>({ok:true,missionId:'mission_demo_001',status:'created',constitution:{...input,purchaseRequiresApproval:input.purchaseRequiresApproval??true}})},
{name:'search_products',description:'Search the AEON product marketplace for every requirement in the active mission, returning multiple candidates, a budget-aware basket, and explicit missing requirements.',inputSchema:{type:'object',properties:{query:{type:'string'},maxPrice:{type:'number'}},required:['query']},execute:async(input)=>{const c=getMissionConstitution();const goal=`${c.goal} ${input.query}`;emitAgentActivity({stage:'REQUESTED',title:'Agent searched marketplace',detail:`search_products → ${input.query}`,tool:'search_products'});const basket=composeBasket(goal,c.budget,c.priorities);emitAgentActivity({stage:'ALLOWED',title:basket.missing.length?'Search completed with gaps':'Mission basket composed',detail:basket.missing.length?`No compliant ${basket.missing.join(', ')} found`:`${basket.selected.length} products selected across ${basket.requirements.length} requirements · ₦${basket.total.toLocaleString()} total`,tool:'search_products'});return {query:input.query,maxPrice:c.budget,...basket,results:basket.requirements.flatMap(r=>r.candidates)}}},
{name:'compare_products',description:'Rank multiple marketplace candidates across all requested mission requirements.',inputSchema:{type:'object',properties:{productIds:{type:'array',items:{type:'string'}},priorities:{type:'array',items:{type:'string'}}},required:['productIds']},execute:async(input)=>{const c=getMissionConstitution();const candidates=searchCatalog('',c.budget).filter(p=>input.productIds.includes(p.id));const ranked=rankForMission(candidates,input.priorities??c.priorities);emitAgentActivity({stage:'ALLOWED',title:'Comparison allowed',detail:`Ranked ${ranked.length} candidates`,tool:'compare_products'});return {ranked,explanation:'Ranking is governed by the active mission constitution.'}}},
{name:'negotiate_offer',description:'Negotiate one or more products while enforcing the active constitution.',inputSchema:{type:'object',properties:{productId:{type:'string'},productIds:{type:'array',items:{type:'string'}},budget:{type:'number'}},required:[]},execute:async(input)=>{const c=getMissionConstitution();const ids:string[]=input.productIds?.length?input.productIds:[input.productId];if(!ids.length)return {status:'error',reason:'PRODUCT_REQUIRED'};if(!c.canNegotiate)return blocked('CONSTITUTION_NEGOTIATION_DISABLED','Negotiation was refused before the negotiation engine executed because this mission does not authorize negotiation.','negotiate_offer');const products=ids.map(id=>searchCatalog('',c.budget).find(p=>p.id===id)).filter(Boolean) as Product[];const results=products.map(p=>negotiate(p,c.budget,c));return {status:'completed',results,total:results.reduce((s,r)=>s+r.acceptedPrice,0),saving:results.reduce((s,r)=>s+r.saving,0)}}},
{name:'request_purchase_approval',description:'Stop before purchase and request an explicit human decision for a single product or multi-product basket.',inputSchema:{type:'object',properties:{productId:{type:'string'},price:{type:'number'},items:{type:'array',items:{type:'object'}},reason:{type:'string'}},required:['price']},execute:async(input)=>{const c=getMissionConstitution();const total=Number(input.price);if(total>c.budget)return blocked('CONSTITUTION_BUDGET_EXCEEDED','Purchase approval cannot be requested for a total above the mission budget.','request_purchase_approval');emitAgentActivity({stage:'REQUESTED',title:'Agent requested purchase approval',detail:`₦${total.toLocaleString()}${input.items?.length?` · ${input.items.length} items`:''}`,tool:'request_purchase_approval'});emitAgentActivity({stage:'ALLOWED',title:'Human checkpoint created',detail:'Purchase requires explicit approval.',tool:'request_purchase_approval'});return {status:'approval_required',humanDecision:true,action:'purchase',...input,totalPrice:total}}}
]
export function registerWebMCP(){const mc=(navigator as any).modelContext;if(!mc?.registerTool)return false;for(const tool of aeonTools)mc.registerTool(tool);return true}
